# Generated by Django 3.1.4 on 2020-12-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201212_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='6', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category', verbose_name='Категория'),
        ),
    ]
