# Generated by Django 3.1.4 on 2020-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Цена'),
        ),
    ]
