# Generated by Django 3.1.4 on 2020-12-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201215_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Курс обучения', 'verbose_name_plural': 'Курсы обучения'},
        ),
    ]
